### ISSUE TITLE
Handing out Badges

### ISSUE THREAD

**Issue by pavelkouril** [pavelkouril/pa165-pkmn-league#64]
("We did not found, how to set the "Beaten?" parameter")

Also, no selectbox for Gym, since Gym Leader can have only one Gym. :)

Just Trainer SelectBox

**Comment by xfaldik** [comment]
Toto je zajimave. Urcite nejsem pro select box - to nedava smysl kdyz musi byt kazda nova gym uz nekomu prirazena. Spis to vidim tak, ze se u GymLeadera v sekci Avaible gyms da edit your gym
